accounts/urls.py
from django.urls import path
from accounts.views import (
    account_view,
    edit_account_view,
    edit_recipe_collection_view
)

app_name = "accounts"

urlpatterns = [
    path('<user_id>/', account_view, name="view"),
    path('<user_id>/edit/', edit_account_view, name="edit"),
    path('update/<pk>/', edit_recipe_collection_view, name="edit-recipe")
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from accounts.views import(
    register_view,
    login_view,
    logout_view,
)

urlpatterns = [
    path('', include('main_app.urls', namespace="home")),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace="account")),
    path('collections/', include('products.urls', namespace="collections")),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('test-kitchen/', include('test_kitchen.urls', namespace="test-kitchen")),   
    path('register/', register_view, name='register'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from .views import (
    recipe_search,
    home_screen_view,
    summer_2022_view,
    RecipeDetail,
)

# from products.views import (
#     # stripe_webhook
# )

app_name = "main_app"

urlpatterns = [
    path('', home_screen_view, name='about'),
    path('recipes/', recipe_search, name='recipes'),
    path('summer2022/', summer_2022_view, name='summer'),
    path('recipes/<pk>/', RecipeDetail.as_view(), name='recipe-detail'),
    # path('webhook/', stripe_webhook, name="stripe-webhook"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from .views import (
    CollectionsView,
    success_view,
    cancel_view,
    CreateCheckoutSessionView,
    # stripe_webhook
)

app_name = "main_app"

urlpatterns = [
    path('success/', success_view, name='success'),
    path('', CollectionsView.as_view(), name='collections'),
    path('cancel/', cancel_view, name='cancel'),
    path('create-checkout-session/<pk>', CreateCheckoutSessionView.as_view(), name="create-checkout-session"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_kitchen/urls.py
from django.urls import path

from test_kitchen.views import (
    test_kitchen_list,
    test_kitchen_create,
    edit_test_kitchen_view,
    TestKitchenDetail,
    test_kitchen_delete,
)

app_name = "test_kitchen"

urlpatterns = [
    path('', test_kitchen_list, name='list'),
    path('create/', test_kitchen_create, name='create'),
    path('<pk>/delete/', test_kitchen_delete, name="delete"),
    path('<pk>/', TestKitchenDetail.as_view(), name='post-detail'),
    path('<pk>/update/', edit_test_kitchen_view, name='edit'),
]

templates/partials/footer.html
{% load static %}

<footer class="footerAppear flex space-btwn  footer-styling">
	<a class="nav-button" href="mailto:youcancookliterallyanything@gmail.com"><p>email</p></a>
	<a class="nav-button" href="https://www.instagram.com/youcancookliterallyanything"><p>instagram</p></a>
	<a class="nav-button" href="https://www.tiktok.com/@yccookliterallyanything?_t=8UigZOgkvHy&_r=1"><p>tiktok</p></a>
</footer>

templates/partials/header.html
{% load static %}
<div class="flex column al-center"> 
	
	<!-- <div class="flex al-center">
		<img class="third auto" src="{% static 'media/exclaimation.png' %}" />
	</div> -->
</div>
<nav class="flex space-btwn mobile-column mobile-al-center header-styling"> 
	<h1 class="cream-text">YCCLA</h1>
	<a class="nav-button nav-button-first" href="{% url 'home:about' %}"><p>About</p></a>
	<a class="nav-button" href="{% url 'collections:collections' %}"><p>Collections</p></a>
	<a class="nav-button" href="{% url 'home:recipes' %}"><p>Recipes</p></a>

	<!-- Theses lines of code will be used when the business expands to allow users to log in -->
	
	<!-- {% if request.user.is_authenticated %}
		{% if request.user.is_recipe_tester %}
			<a class="" href="{% url 'test-kitchen:list' %}"><h2>Test Kitchen</h2></a>
		{% endif %}
		<a class="" href="{% url 'account:view' user_id=request.user.id %}"><h2>My Profile</h2></a>
		<a class="" href="{% url 'logout' %}"><h2>Logout</h2></a>
	{% else %}
		<a class="" href="{% url 'login' %}"><h2>Login</h2></a>
		<a class="" href="{% url 'register' %}"><h2>Register</h2></a>
	{% endif %}	 -->
</nav>