backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from accounts.views import(
    register_view,
    login_view,
    logout_view,
)

urlpatterns = [
    path('', include('main_app.urls', namespace="home")),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace="account")),
    path('collections/', include('products.urls', namespace="collections")),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('test-kitchen/', include('test_kitchen.urls', namespace="test-kitchen")),   
    path('register/', register_view, name='register'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from .views import (
    recipe_search,
    home_screen_view,
    summer_2022_view,
    RecipeDetail,
)

# from products.views import (
#     # stripe_webhook
# )

app_name = "main_app"

urlpatterns = [
    path('', home_screen_view, name='about'),
    path('recipes/', recipe_search, name='recipes'),
    path('summer2022/', summer_2022_view, name='summer'),
    path('recipes/<pk>/', RecipeDetail.as_view(), name='recipe-detail'),
    # path('webhook/', stripe_webhook, name="stripe-webhook"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from accounts.models import CustomUser, RecipeCollection

class RegistrationForm(UserCreationForm):

    email = forms.EmailField(max_length=255, help_text="Required. Add a valid email address.")

    class Meta:
        model = CustomUser
        fields = ('email', 'username', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = CustomUser.objects.get(email=email)
        except CustomUser.DoesNotExist:
            return email
        raise forms.ValidationError(f"Email {email} is already in use.")

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        try:
            username = CustomUser.objects.get(username=username)
        except Exception as e:
            return username
        raise forms.ValidationError(f"Email {username} is already in use.")
    
class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = CustomUser
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")

class AccountUpdateForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'fname', 'lname', 'bio')

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = CustomUser.objects.exclude(pk=self.instance.pk).get(email=email)
        except CustomUser.DoesNotExist:
            return email
        raise forms.ValidationError(f"Email {email} is already in use.")

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            username = CustomUser.objects.exclude(pk=self.instance.pk).get(username=username)
        except CustomUser.DoesNotExist:
            return username
        raise forms.ValidationError(f"Username {username} is already in use.")

    def save(self, commit=True):
        account = super(AccountUpdateForm, self).save(commit=False)
        account.username = self.cleaned_data['username']
        account.email = self.cleaned_data['email'].lower()
        account.fname = self.cleaned_data['fname']
        account.lname = self.cleaned_data['lname']
        account.bio = self.cleaned_data['bio']
        if commit:
            account.save()
        return account

class RecipeCollectionCreate(forms.ModelForm):

    class Meta:
        model = RecipeCollection
        fields = ('recipe', 'sent', 'sent_to', 'received', 'received_from', 'user')

class RecipeCollectionUpdateForm(forms.ModelForm):

    class Meta:
        model = RecipeCollection
        fields = ('sent', 'sent_to', 'received', 'received_from')

    def save(self, commit=True):
        collection = super(RecipeCollectionUpdateForm, self).save(commit=False)
        collection.sent = self.cleaned_data['sent']
        collection.sent_to = self.cleaned_data['sent_to']
        collection.received = self.cleaned_data['received']
        collection.received_from = self.cleaned_data['received_from']

        if commit:
            print('form save')
            collection.save()
        return collection

templates/password_reset/password_change.html
{% extends 'base.html' %}

{% block body %}

<div class="page-height flex center al-center">
  <div class="double-border red-border">
    <form id="id_password_change_form" method="POST" class="flex column extra-padding red-border">
        {% csrf_token %}
        <h2 class="">Change password</h2>
        <input name="old_password" class="flex space-btwn baseline margin-top" placeholder="Old password" type="password" id="id_old_password" required="true">
        <input name="new_password1" class="flex space-btwn baseline margin-top" placeholder="New password" type="password" id="id_new_password1" required="true">
        <input name="new_password2" class="flex space-btwn baseline margin-top" placeholder="Confirm password" type="password" id="id_new_password2" required="true">

        {% for field in form %}
          {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
        {% endfor %}

      <button id="id_submit_btn" class="stnd-bttn red-border padding margin-top" type="submit">Update</button>  
    </form>
  </div>
</div>


{% endblock %}

templates/password_reset/password_change_done.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been Updated.</p>
	</div>
</div>

{% endblock %}

templates/password_reset/password_email_email.html
{% autoescape off %}
To initiate the password reset process for your Account {{ user.email }},
click the link below:

{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
You Can Cook Literally Anything
{% endautoescape %}

templates/password_reset/password_reset_complete.html
   
{% extends 'base.html' %}


{% block body %}

<div class="container">
	<div class="d-flex flex-column">
		<p class="m-auto">Your password has been reset. You may go ahead and <a href="{% url 'login' %}">sign in</a> now.</p>
	</div>
</div>

{% endblock %}

templates/password_reset/password_reset_done.html
   
{% extends 'base.html' %}

{% block body %}

<div class="container">

	<div class="d-flex flex-column">
		  <p class="m-auto p-2">
		    We've emailed you instructions for setting your password, if an account exists with the email you entered.
		    You should receive them shortly.
		  </p>
		  <p class="m-auto p-2">
		    If you don't receive an email, please make sure you've entered the address you registered with,
		    and check your spam folder.
		  </p>
		  <p class="m-auto p-2"><a href="{% url 'home:about' %}">Return to home page</a></p>
	</div>
</div>

{% endblock %}

templates/password_reset/password_reset_form.html
{% extends 'base.html' %}


{% block body %}

<form id="id_password_reset_form" method="POST" class="">
    {% csrf_token %}
  <h1 class="">Reset password</h1>
    <input name="email" class="" placeholder="Email address" type="email" id="id_email" required="true" >
  <button id="id_submit_btn" class="" >Send reset email</button>  
</form>



{% endblock %}