accounts/urls.py
from django.urls import path
from accounts.views import (
    account_view,
    edit_account_view,
    edit_recipe_collection_view
)

app_name = "accounts"

urlpatterns = [
    path('<user_id>/', account_view, name="view"),
    path('<user_id>/edit/', edit_account_view, name="edit"),
    path('update/<pk>/', edit_recipe_collection_view, name="edit-recipe")
]

backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from accounts.views import(
    register_view,
    login_view,
    logout_view,
)

urlpatterns = [
    path('', include('main_app.urls', namespace="home")),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace="account")),
    path('collections/', include('products.urls', namespace="collections")),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('test-kitchen/', include('test_kitchen.urls', namespace="test-kitchen")),   
    path('register/', register_view, name='register'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_reset/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='password_reset/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_kitchen/urls.py
from django.urls import path

from test_kitchen.views import (
    test_kitchen_list,
    test_kitchen_create,
    edit_test_kitchen_view,
    TestKitchenDetail,
    test_kitchen_delete,
)

app_name = "test_kitchen"

urlpatterns = [
    path('', test_kitchen_list, name='list'),
    path('create/', test_kitchen_create, name='create'),
    path('<pk>/delete/', test_kitchen_delete, name="delete"),
    path('<pk>/', TestKitchenDetail.as_view(), name='post-detail'),
    path('<pk>/update/', edit_test_kitchen_view, name='edit'),
]

accounts/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from accounts.models import CustomUser, RecipeCollection

class RegistrationForm(UserCreationForm):

    email = forms.EmailField(max_length=255, help_text="Required. Add a valid email address.")

    class Meta:
        model = CustomUser
        fields = ('email', 'username', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = CustomUser.objects.get(email=email)
        except CustomUser.DoesNotExist:
            return email
        raise forms.ValidationError(f"Email {email} is already in use.")

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        try:
            username = CustomUser.objects.get(username=username)
        except Exception as e:
            return username
        raise forms.ValidationError(f"Email {username} is already in use.")
    
class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = CustomUser
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")

class AccountUpdateForm(forms.ModelForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'fname', 'lname', 'bio')

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = CustomUser.objects.exclude(pk=self.instance.pk).get(email=email)
        except CustomUser.DoesNotExist:
            return email
        raise forms.ValidationError(f"Email {email} is already in use.")

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            username = CustomUser.objects.exclude(pk=self.instance.pk).get(username=username)
        except CustomUser.DoesNotExist:
            return username
        raise forms.ValidationError(f"Username {username} is already in use.")

    def save(self, commit=True):
        account = super(AccountUpdateForm, self).save(commit=False)
        account.username = self.cleaned_data['username']
        account.email = self.cleaned_data['email'].lower()
        account.fname = self.cleaned_data['fname']
        account.lname = self.cleaned_data['lname']
        account.bio = self.cleaned_data['bio']
        if commit:
            account.save()
        return account

class RecipeCollectionCreate(forms.ModelForm):

    class Meta:
        model = RecipeCollection
        fields = ('recipe', 'sent', 'sent_to', 'received', 'received_from', 'user')

class RecipeCollectionUpdateForm(forms.ModelForm):

    class Meta:
        model = RecipeCollection
        fields = ('sent', 'sent_to', 'received', 'received_from')

    def save(self, commit=True):
        collection = super(RecipeCollectionUpdateForm, self).save(commit=False)
        collection.sent = self.cleaned_data['sent']
        collection.sent_to = self.cleaned_data['sent_to']
        collection.received = self.cleaned_data['received']
        collection.received_from = self.cleaned_data['received_from']

        if commit:
            print('form save')
            collection.save()
        return collection

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout
from accounts.forms import RegistrationForm, AccountAuthenticationForm, AccountUpdateForm, RecipeCollectionCreate, RecipeCollectionUpdateForm
from django.conf import settings

from accounts.models import CustomUser
from test_kitchen.models import TestKitchenPost
from .models import Recipe, RecipeCollection

# Create your views here.

def register_view(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        return HttpResponse(f"You are already authenticated as {user.email}.")
    context = {}

    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email').lower()
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            destination = get_redirect_if_exists(request)
            if destination:
                return redirect(destination)
            return redirect('home:recipes') #redirects to url with the name 'home' in backend/urls.py

        else: 
            context['registration_form'] = form

    return render(request, 'accounts/register.html', context)

def logout_view(request):
    logout(request)
    return redirect('home:about')

def login_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if user.is_authenticated:
        return redirect('account:view', user_id=user.pk)
    
    destination = get_redirect_if_exists(request)
    if request.POST:
        form = AccountAuthenticationForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                if destination:
                    return redirect(destination)
                return redirect('account:view', user_id=user.pk)
        else:
            context['login_form'] = form
    return render(request, "accounts/login.html", context)

def get_redirect_if_exists(request):
    redirect = None
    if request.GET:
        if request.GET.get('next'):
            redirect = str(request.GET.get('next'))
    return redirect

def account_view(request, *args, **kwargs):
        
    context = {}
    user_id =  kwargs.get('user_id')
    try: 
        account = CustomUser.objects.get(pk=user_id)
    except  CustomUser.DoesNotExist:
        return HttpResponse('That user does not exist.')
    if account: 
        context['id'] = account.id
        context['username'] = account.username
        context['email'] = account.email
        context['hide_email'] = account.username
        context['bio'] = account.bio
        context['fname'] = account.fname
        context['lname'] = account.lname
        context['posts'] = TestKitchenPost.objects.filter(user=account.id)
        context['postcards'] = RecipeCollection.objects.filter(user=account.id)

        is_self = True
        is_friend = False
        user = request.user

        if user.is_authenticated and user != account: 
            is_self = False
        elif not user.is_authenticated:
            is_self = False 

        context['is_self'] = is_self
        context['is_friend'] = is_friend
        context['BASE_URL'] = settings.BASE_URL
    
    # CREATE RECIPE COLLECTION
    # if not user.is_authenticated:
    #     return redirect('login')
    # else:        
    #     context['recipes'] = Recipe.objects.all()

    #     if request.POST:
    #         form = RecipeCollectionCreate(request.POST)
    #         print(form)
    #         if form.is_valid():
    #             form.save()
    #             print('success')
    #             destination = get_redirect_if_exists(request)
    #             if destination:
    #                 return redirect(destination)
    #         return redirect('account:view', user_id=user.pk)

    # # CREATE RECIPE COLLECTION
    if not user.is_authenticated:
        return redirect('login')
    else:        
        context['recipes'] = Recipe.objects.all()
        form = RecipeCollectionCreate(request.POST)

        if request.POST and not form.is_valid():
            print('update')
            # collection_id = pk
            collection = RecipeCollection.objects.filter(user=account.id)
            update_form = RecipeCollectionUpdateForm(request.POST)
            if request.POST:
                print('update', update_form)
                if update_form.is_valid():
                    print('view update')
                    update_form.save()
                    return redirect('account:view', user_id=user.pk)
                # else: 
                #     update_form = RecipeCollectionUpdateForm(request.POST, instance=request.user,
                #         initial = {
                #             "id": collection.pk,
                #             "sent": collection.sent,
                #             "sent_to": collection.sent_to,
                #             "received": collection.received,
                #             "received_from": collection.received_from,
                #         }
                #     )
                    # context['form'] = form
            # else: 
            #     update_form = RecipeCollectionUpdateForm(
            #             initial = {
            #                 "id": collection.pk,
            #                 "sent": collection.sent,
            #                 "sent_to": collection.sent_to,
            #                 "received": collection.received,
            #                 "received_from": collection.received_from,
            #             })
            #     context['form'] = update_form
        elif request.POST:
            print('create')
            print(form)
            if form.is_valid():
                form.save()
                print('success')
                destination = get_redirect_if_exists(request)
                if destination:
                    return redirect(destination)
            return redirect('account:view', user_id=user.pk)
            # else:
            #     form = RecipeCollectionCreate(prefix="create")
        
        
    return render(request, "accounts/account.html", context)

def edit_account_view(request, *args, **kwargs):

    if not request.user.is_authenticated:
        return redirect('login')
    user_id =  kwargs.get('user_id')
    # account = CustomUser.objects.get(pk=user_id)
    try: 
        account = CustomUser.objects.get(pk=user_id)
    except  CustomUser.DoesNotExist:
        return HttpResponse('Something went wrong.')
    if account.pk != request.user.pk:
        return HttpResponse('You cannot edit someone elses profile.')
    context = {}
    if request.POST:
        form = AccountUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('account:view', user_id=account.pk)
        else: 
            form = AccountUpdateForm(request.POST, instance=request.user,
                initial = {
                    "id": account.pk,
                    "email": account.email,
                    "username": account.username,
                    "fname": account.fname,
                    "lname": account.lname,
                    "bio": account.bio,
                }
            )
            context['form'] = form
    else: 
        form = AccountUpdateForm(
                initial = {
                    "id": account.pk,
                    "email": account.email,
                    "username": account.username,
                    "fname": account.fname,
                    "lname": account.lname,
                    "bio": account.bio,
                })
        context['form'] = form

    return render(request, "accounts/edit_account.html", context)

def edit_recipe_collection_view(request, pk):
    user = request.user
    user_id =  request.user.id
    context = {}
    postcard_id = pk
    postcard = RecipeCollection.objects.get(pk=postcard_id)
    form = RecipeCollectionUpdateForm(request.POST, instance=postcard)

    if not user.is_authenticated:
        return redirect('login')
    if request.POST:
        print('update', form)
        if form.is_valid():
            print('view update')
            form.save()
            return redirect('account:view', user_id=user.pk)
        else: 
            form = RecipeCollectionUpdateForm(request.POST, instance=request.user,
                initial = {
                    "id": postcard.pk,
                    "recipe": postcard.recipe,
                    "sent": postcard.sent,
                    "sent_to": postcard.sent_to,
                    "received": postcard.received,
                    "received_from": postcard.received_from,
                    }
                )
            context['form'] = form
    else: 
        form = RecipeCollectionUpdateForm(
            initial = {
                "id": postcard.pk,
                "recipe": postcard.recipe,
                "sent": postcard.sent,
                "sent_to": postcard.sent_to,
                "received": postcard.received,
                "received_from": postcard.received_from,
            })
        context['form'] = form
    
    return render(request, "accounts/postcard_update.html", context)

accounts/templates/accounts/account.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<div class="flex margin-top space-btwn full-width">
    <div class="double-border bg-blue cream-border">
        <div class="prof-height prof-width flex column space-btwn padding bg-blue cream-border">
            <div>
                <h3 class="cream-text">{{fname}} {{lname}}</h3>
                <h4 class="cream-text margin-top">Email</h4>
                {%  if is_self %}
                    <p class="cream-text no-margin">{{email}}</p>
                {% else %}
                {% if hide_email %}
                    <p class="cream-text no-margin">**********</p>
                {% else %}
                    <p class="cream-text no-margin">{{email}}</p>
                {% endif %}
                {% endif %}
                <h4 class="cream-text margin-top">Username</h4>
                <p class="cream-text no-margin">{{username}}</p>
                <h4 class="cream-text margin-top">Bio</h4>
                <p class="cream-text no-margin">{{bio}}</p>
            </div>
            <!-- If Auth user is viewing their own profile -->
            {% if is_self %}
                <div class="flex column col-center">
                    <a  href="{% url 'account:edit' user_id=id %}"><button class="prof-bttn red-border padding margin-top">Update</button></a>
                    <a  href="{% url 'password_change' %}"><button class="prof-bttn red-border padding margin-top">Change password</button></a>
                </div>
            {% endif %}
        </div>
    </div>
    <div class="flex column">
        <div class="flex space-btwn sixty">
            {% if user.is_recipe_tester %}
            <div class="tab-red flex al-center pointer">
                <h2 onClick={toggleTab(id)} id="postcards" class="no-margin">My Postcards</h2>
            </div>
            {% else %}
            <div class="tab-red flex al-center">
                <h2 class="no-margin">My Postcards</h2>
            </div>
            {% endif %}
            {% if user.is_recipe_tester %}
            <div class="tab-blue flex al-center pointer">
                <h2 onClick={toggleTab(id)} id="posts" class="no-margin">My Posts</h2>
            </div>
            {% endif %}
        </div> 
        <div class="red-border-three prof-tab-height column" id="postcards-tab">
            <div class="flex space-btwn">
                <div class="tab-red-left"></div>
                <div class="tab-red-right"></div>
            </div>
            <!-- CREATE FORM  -->
            <form class="flex padding space-btwn" method="POST">
                {% csrf_token %}
                <div class="flex column">
                    <div class="flex al-center">
                        <p class="flex space-btwn margin-top">Add to my collection: </p>
                        <select class="margin-left" name="recipe">
                            {% for recipe in recipes %}
                            <option>{{ recipe.title }}</option>
                            {% endfor %}
                        </select>   
                    </div>
                    <div class="flex baseline">
                        <label class="container">Sent
                            <input  
                                class="container-input"
                                type="checkbox"
                                name="sent"
                            >
                            <span class="checkmark"></span>
                        </label>
                            <p class="flex space-btwn baseline no-margin">Sent to:</p>
                            <input  
                                class="margin-left"
                                type="textarea"
                                name="sent_to"
                                placeholder="Please share your experience"
                            >     
                    </div>
                    <div class="flex baseline no-margin">
                        <label class="container">Received
                            <input  
                                class="container-input"
                                type="checkbox"
                                name="received"
                            >
                            <span class="checkmark"></span>
                        </label>
                        <p class="flex space-btwn baseline no-margin">Received from:</p>
                        <input  
                            class="margin-left"
                            type="text"
                            name="received_from"
                            placeholder="Please share your experience"
                        >    
                    </div>
                    <input  
                        value="{{id}}"
                        type="hidden"
                        name="user"
                    >
                </div>
                <div class="flex flex-end">
                        <button class="prof-bttn red-border margin-top" type="submit" name="btn" value="Create">New Recipe Collected</button>
                </div>
            </form>
            <!-- UPDATE FORM  -->
            {% for postcard in postcards %} 
            <div class="flex padding space-btwn" method="POST">
                {% csrf_token %}
                <div class="flex column full">
                    <p class="HWT-small no-margin" >{{ postcard.recipe }}</p>                
                    <div class="flex baseline">
                        {% if postcard.sent %}
                        <label class="container">Sent
                            <span class="checkmark-filled"></span>
                        </label>
                        {% else %}
                        <label class="container">Sent
                            <span class="checkmark-empty"></span>
                        </label>
                        {% endif %}
                        <p class="no-margin">Sent to: {{ postcard.sent_to}}</p>
                    </div>
                    <div class="flex baseline">
                        {% if postcard.received %}
                            <label class="container">Received
                                <span class="checkmark-filled"></span>
                            </label>
                        {% else %}
                            <label class="container">Received
                                <span class="checkmark-empty"></span>
                            </label>
                        {% endif %}
                        <p class="no-margin">Received from: {{ postcard.received_from }}</p>
                    </div>
                </div>
                <div class="flex flex-end">
                    <a href="../update/{{postcard.pk}}/"><button class="prof-bttn red-border margin-top" type="submit">Update</button></a>
                </div>
            </div> 
            <!-- <form class="flex padding space-btwn" method="POST">
                {% csrf_token %}
                <div class="flex column full">
                    <p class="HWT-small no-margin" >{{ postcard.recipe }}</p>                
                    <div class="flex baseline">
                        {% if postcard.sent %}
                        <label class="container">Sent
                            <input  
                                class="container-input"
                                type="checkbox"
                                name="sent"
                                checked
                            >
                            <span class="checkmark"></span>
                        </label>
                        {% else %}
                        <label class="container">Sent
                            <input  
                                class="container-input"
                                type="checkbox"
                                name="sent"
                            >
                            <span class="checkmark"></span>
                        </label>
                        {% endif %}
                        <p class="no-margin">Sent to: </p>
                        <input  
                            class="margin-left"
                            type="text"
                            name="sent_to"
                            placeholder="{{ postcard.sent_to}}"
                        > 
                    </div>
                    <div class="flex baseline">
                        {% if postcard.received %}
                            <label class="container">Received
                                <input  
                                    class="container-input"
                                    type="checkbox"
                                    name="received"
                                    checked
                                >
                                <span class="checkmark"></span>
                            </label>
                        {% else %}
                            <label class="container">Received
                                <input  
                                    class="container-input"
                                    type="checkbox"
                                    name="received"
                                >
                                <span class="checkmark"></span>
                            </label>
                        {% endif %}
                        <p class="no-margin">Received from: </p>
                        <input  
                            class="margin-left"
                            type="text"
                            name="received_from"
                            placeholder="{{ postcard.received_from }}"
                        > 
                    </div>
                </div>
                <input  
                    value="{{postcard.pk}}"
                    type="hidden"
                    name="id"
                > 
                <div class="flex flex-end">
                    <button class="prof-bttn red-border margin-top" type="submit" name="btn" value="Update">Update</button>
                </div>
            </form> -->
            {% endfor %}            
        </div>
        <div>
            {% if request.user.is_recipe_tester %}
            <div class="bg-blue red-border-three prof-tab-height column" style="display: none"  id="posts-tab">
                <div class="flex space-btwn">
                    <div class="tab-blue-left"></div>
                    <div class="tab-blue-right"></div>
                </div>
                <div class="flex column padding">  
                    <div class="flex space-btwn  al-center">
                        <a  class="" href="{% url 'test-kitchen:create' %}"><button class="stnd-bttn red-border bg-cream padding margin-top">New Post</button></a>
                    </div>
                    {% for post in posts %}
                        {% if post.user.pk == user.pk %}
                        <div class="padding margin-top bg-cream red-border">
                            <div class="flex space-btwn">
                                <h2>{{ post.title }}</h2>
                                <p> {{ post.date }}</p>
                            </div>
                            <p> {{ post.post }}</p>
                            <a  href="../../test-kitchen/{{post.pk}}/update/"><button class="prof-bttn red-border padding margin-top">Edit post</button></a>
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock body %}

accounts/templates/accounts/edit_account.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<div class="page-height flex center al-center">
    <div class="double-border red-border">
        <form class="flex column padding red-border" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>Update Profile</h2>
            <h4 class="margin-top">Email</h4>
            <input type="email" name="email" id="id_input_email" class="flex space-btwn baseline" placeholder="Email address" required value={{form.initial.email}}>
            <h4 class="margin-top">Username</h4>
            <input type="text" name="username" id="id_input_username" class="flex space-btwn baseline" placeholder="Username" required value={{form.initial.username}}>
            <h4 class="margin-top">Bio</h4>
            <input type="text" name="bio" id="id_input_bio" class="flex space-btwn baseline" placeholder="Bio" required value="{{form.initial.bio}}">
            <h4 class="margin-top">First Name</h4>
            <input type="text" name="fname" id="id_input_fname" class="flex space-btwn baseline" placeholder="First Name" required value="{{form.initial.fname}}">
            <h4 class="margin-top">Last Name</h4>
            <input type="text" name="lname" id="id_input_lname" class="flex space-btwn baseline" placeholder="Last Name" required value="{{form.initial.lname}}">
            {% for field in login_form %}
            {% for error in field.errors %}
            {% if error == ' ' %}
                <p style="display: none">{{ error }}</p>
                {% else %}
                <p style="color: red">{{ error }}</p>
                {% endif %}
            {% endfor %}
            {% endfor %}
            {% if form.non_field_errors %}
                <div style="color: red">
                    <p>{{form.non_field_errors}}</p>
                </div>
            {% endif %}
            <div class="flex center">
                <button class="stnd-bttn red-border padding margin-top" type="submit">Update</button>
            </div>
        </form>
    </div>
</div>

{% endblock body %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<div class="page-height flex center al-center">
    <div class="double-border red-border">
        <form class="flex column extra-padding red-border" method="post">
            {% csrf_token %}
			<input class="flex space-btwn baseline margin-top" type="email" name="email" id="inputEmail" placeholder="Email address" required>
			<input class="flex space-btwn baseline margin-top" type="password" name="password" id="inputPassword" placeholder="Password" required>
			{% for field in login_form %}
            {% for error in field.errors %}
                {% if error == ' ' %}
                <p style="display: none">{{ error }}</p>
                {% else %}
                <p style="color: red">{{ error }}</p>
                {% endif %}
            {% endfor %}
			{% endfor %}
			{% if login_form.non_field_errors %}
			<div style="color: red">
			<p>{{login_form.non_field_errors}}</p>
			</div>
			{% endif %}
			<button class="stnd-bttn red-border padding margin-top" type="submit">Log in</button>
		</form>
		<div class="flex center">
			<a href="{% url 'password_reset' %}"><p>Reset password</p></a>
		</div>
	</div>
</div>

{% endblock body %}